---
name: Repository Updater

# yamllint disable-line rule:truthy
on:
  workflow_call:
    secrets:
      UPDATER_TOKEN:
        required: true

permissions:
  contents: read

concurrency:
  group: queue

jobs:
  publish:
    name: Publish app update
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Run Repository Updater
        uses: lazytarget-homeassistant-apps/repository-updater@main
        with:
          token: ${{ secrets.UPDATER_TOKEN }}
          app: ${{ github.event.client_payload.app }}
          repository: ${{ github.repository }}
          sha: ${{ github.event.client_payload.sha }}
